version: '3.5'

services:
  trabajofinal-web:
    container_name: trabajofinal-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 350:80
    volumes:
      - ./public:/var/www/trabajofinal/public
    depends_on:
      - trabajofinal-be
    networks:
      - trabajofinal-network

  trabajofinal-be:
    container_name: trabajofinal-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005
    volumes:
      - ./:/var/www/trabajofinal
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - trabajofinal-db
    networks:
      - trabajofinal-network

  trabajofinal-db:
    container_name: trabajofinal-db
    build:
      context: ./docker/database
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: trabajofinal_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - trabajofinal-db-data:/var/lib/mysql
    networks:
      - trabajofinal-network

volumes:
  trabajofinal-db-data:

networks:
  trabajofinal-network:
    external: true